version: "3.4"
services:
    testdockerforwebapi:
        image: ${DOCKER_REGISTRY-}testdockerforwebapi
        build:
          context: .
          dockerfile: TestDockerForWebApi/Dockerfile
        ports:
          - "1234:80"
        depends_on:
          - db
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - "1443:1443"
        environment:
            ACCEPT_EULA: "Y"