version: '3.4'

services:
  testdockerforwebapi:
    image: ${DOCKER_REGISTRY-}testdockerforwebapi
    build:
      context: .
      dockerfile: TestDockerForWebApi/Dockerfile
    ports:
        - 9000:80
      
  sql.data:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
    volumes:  
        - ./data/mssql:/var/opt/mssql3  
    ports:
        - "34008:34008"  