// <auto-generated />
using DemoAPI0001.Models.DataContextDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAPI0001.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220728093639_InitialValue")]
    partial class InitialValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoAPI0001.Models.Class.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Job = "Warrior",
                            Name = "Draco"
                        },
                        new
                        {
                            Id = 2,
                            Job = "Archer",
                            Name = "William"
                        },
                        new
                        {
                            Id = 3,
                            Job = "Wizard",
                            Name = "John"
                        },
                        new
                        {
                            Id = 4,
                            Job = "Fighter",
                            Name = "Mark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
